version: "3.8"

services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview_flow_db
    ports:
      - "5433:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: