services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres17
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-interview_flow_db}
    ports:
      - "${DB_LOCAL_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
