version: "3.8"

services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: postgres17
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-interview_flow_db}
    ports:
      - "5433:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: