databaseChangeLog:
  - changeSet:
      id: 002-create-applications-table
      author: you@example.com
      changes:
        - createTable:
            tableName: applications
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(20)
                  constraints:
                    nullable: false
              - column:
                  name: company_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: company_link
                  type: VARCHAR(512)
              - column:
                  name: position
                  type: VARCHAR(255)
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
        - addForeign
