spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}:${DATASOURCE_PORT}/${DATASOURCE_DB}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
aws:
  region: ${AWS_REGION}
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
