spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start_and_stop
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
