spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start_and_stop
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  # Email Configuration for Development
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME:interviewflowcorp@gmail.com}
    password: ${MAIL_PASSWORD:gwtdkpzzvybetiza}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

# Application-specific configuration for Development
app:
  notification:
    batch-size: 50
    enabled: true