spring:
  application:
    name: InterviewFlow
  profiles:
    active: @spring.profiles.active@
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  # Enable scheduling
  task:
    scheduling:
      pool:
        size: 2