spring:
  docker:
    compose:
      enabled: true
      file: docker-compose-prod.yml
      lifecycle-management: start_and_stop
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
## TODO remove docker compose and change datasource after onboarding AWS Aurora
#  docker:
#    compose:
#      enabled: false
#  datasource:
#    url: ${DATASOURCE_URL}
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
aws:
  region: ${AWS_REGION}
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
