spring:
  application:
    name: InterviewFlow
  profiles:
    active: @spring.profiles.active@
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  task:
    scheduling:
      pool:
        size: 2
interviewFlow:
  frontend:
    frontendDomain: ${FRONTEND_URL}
