spring:
  application:
    name: InterviewFlow
  profiles:
    active: @spring.profiles.active@
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

interviewFlow:
  frontend:
    frontendDomain: ${FRONTEND_URL}